FROM public.ecr.aws/lambda/python:3.12

COPY requirements.txt ${LAMBDA_TASK_ROOT}/
RUN pip install --no-cache-dir -r requirements.txt

COPY alembic.ini ${LAMBDA_TASK_ROOT}/
COPY alembic/ ${LAMBDA_TASK_ROOT}/alembic/
COPY app/ ${LAMBDA_TASK_ROOT}/app/
COPY migrate.py ${LAMBDA_TASK_ROOT}/

CMD ["migrate.handler"]
